
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&&useSSL=false&amp&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: admin
  jackson:
    serialization:
      indent_output: true
  redis:
    cache.clusterNodes: 127.0.0.1:6379
    cache.commandTimeout: 5000

#management:
#  endpoints:
#    web:
#      exposure:
#        include:  health,info,beans # 健康监控信息
mybatis:
  mapper-locations: classpath:com/jsq/demo/dao/*Mapper.xml
  config-location:
    classpath: mybatis-config.xml
#  mapper-locations: classpath*:com.jsq.demo.dao/**.xml

server:
  port: 8088
